#!/usr/bin/python

import os,sys

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

# add the lib path
sys.path.append(os.path.join(os.getenv("OPENSHIFT_REPO_DIR"), "libs"))  

from mybottleapp import application
